name: Build-Release
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - run: pnpm i
      - run: pnpm run make
      - uses: softprops/action-gh-release@v2
        with:
          files: out/**/*.exe
